# Usage: tox -e format
[tox]
envlist = format, lint, tests

[testenv:format]
description = Run ruff for formatting and linting autofixes
skip_install = true
deps =
    ruff
    ty
commands =
    ruff check --fix video_preprocessing main.py
    ruff check --select I --fix video_preprocessing main.py
    ruff format video_preprocessing main.py

[testenv:lint]
description = Run lints and type checker
skip_install = true
deps =
    ruff
    ty
commands =
    ruff format --check video_preprocessing main.py
    ruff check video_preprocessing main.py
    ruff check --select I video_preprocessing main.py
    ty check --python .venv/Scripts/python.exe video_preprocessing

[testenv:tests]
description = Run pytest with coverage
deps =
    pytest
    pytest-cov
commands =
    pytest --maxfail=1 --disable-warnings -q --cov=video_preprocessing --cov-report=term-missing
